In [ ]:
#Name:Samin Thapa
#Student ID:2408644
#Problem 1
#Task1
import numpy as np
array = np.empty((2,2))
print(array)

[[6.71893515e-310 0.00000000e+000]
 [6.71789574e-310 6.71789574e-310]]


In [ ]:
#Task2
array = np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Task3
fill_value = 10
array = np.full((3,3), fill_value)
print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#Task4
array = np.array([[1,2,3],[3,2,1]])
zeros_like = np.zeros_like(array)
print(zeros_like)


[[0 0 0]
 [0 0 0]]


In [ ]:
#Task5
ones_like = np.ones_like(array)
print(ones_like)

[[1 1 1]
 [1 1 1]]


In [ ]:
#Task6
new_list = [1,2,3,4]
np_array  = np.array(new_list)
print(np_array)


[1 2 3 4]


In [ ]:
#Problem 2
#Task1
array = np.arange(10 ,49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#Task2
array = np.random.randint(0,8,size=(9))
second_array = array.reshape(3,3)
print(second_array)

[[2 1 0]
 [6 2 5]
 [1 6 5]]


In [ ]:
#Task3
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Task4
array = np.random.random(30)
mean = array.mean()
print("The random array is \n",array)
print("Mean is",mean)

The random array is 
 [0.91324095 0.12653248 0.1289755  0.63000172 0.36338882 0.55165794
 0.31197142 0.42211361 0.89259894 0.6451595  0.12481869 0.16747183
 0.27537566 0.64920577 0.62016393 0.86698658 0.35500863 0.38362486
 0.5396206  0.01058672 0.99579343 0.80714795 0.71573526 0.69772826
 0.75578462 0.34232222 0.60977973 0.62322238 0.15011849 0.74721969]
Mean is 0.5141118725891203


In [ ]:
#Task5
array = np.random.randint(0,100,size=(10,10))
print(array)

min = np.min(array)
max = np.max(array)

print("Maximjm value is",array.max())
print("Minimum value is",array.min())

[[50 24 20 91 67 30 59 15 31 96]
 [55 80 18 56 84 41  1 27 19 73]
 [18 24 85 73 46 80 92 81 69 94]
 [81 61  9 41 69 27 92 35 68 33]
 [96 61 58 80 20  1  9 40 35 25]
 [36 85 11 94 27 14 74 90 29 47]
 [51 19 96 69 54 65 31 90 76 88]
 [ 8 54  8 87 78 40 33 17 45 15]
 [46 57 69 34 10 28 62 68 86 20]
 [64 43 70 94 57  9 77 94 18 25]]
Maximjm value is 96
Minimum value is 1


In [ ]:
#Task6
array = np.zeros(10)
array[-6] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Task7
arr = [1,2,0,0,4,0]
reversed_array = arr[::-1]
print(reversed_array)

[0, 4, 0, 0, 2, 1]


In [18]:
#Task8
import numpy as np

rows = 5
cols = 4
arr = np.zeros((rows, cols))

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Task9
import numpy as np

arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            arr[i, j] = 0
        else:
            arr[i, j] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
#Problem 3
#Task1
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

print("Addition of x and y is:\n", np.add(x,y))

print("Addition of v and w is:\n", np.add(v,w))

Addition of x and y is:
 [[ 6  8]
 [10 13]]
Addition of v and w is:
 [20 22]


In [10]:
#Task2
print("Subtraction of x and y:\n", np.subtract(x,y))

print("Subtraction of v and w:\n", np.subtract(v,w))

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Subtraction of v and w:
 [-2 -2]


In [13]:
#Task3
print("Product of x with 2 is:\n", np.multiply(x,2))
print("Product of y with 8 is:\n", np.multiply(y,8))
print("Product of v with 3 is:", np.multiply(v,3))
print("Produc of w with 4 is:", np.multiply(w,4))

Product of x with 2 is:
 [[ 2  4]
 [ 6 10]]
Product of y with 8 is:
 [[40 48]
 [56 64]]
Product of v with 3 is: [27 30]
Produc of w with 4 is: [44 48]


In [14]:
#Task4
print("Square of elements in x is:\n", np.square(x))
print("Square of elements in y is:\n", np.square(y))
print("Square of elements in v is:\n", np.square(v))
print("Square of elements in w is:\n", np.square(w))

Square of elements in x is:
 [[ 1  4]
 [ 9 25]]
Square of elements in y is:
 [[25 36]
 [49 64]]
Square of elements in v is:
 [ 81 100]
Square of elements in w is:
 [121 144]


In [15]:
#Task5
dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)

dot_x_v = np.dot(x, v)
print("Dot product of x and v:\n", dot_x_v)

dot_x_y = np.dot(x, y)
print("Dot product of x and y:\n", dot_x_y)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [16]:
#Task6
concatOne = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concatOne)

concatTwo = np.vstack((v, w)).T
print("Concatenation of v and w along columns:\n", concatTwo)

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


In [17]:
#Task7
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_x_v)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [19]:
#Problem 4
#Task1
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Number 1: Proving A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:\n", identity_matrix)

# Number 2: Proving AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA?", are_equal)

# Number 3: Proving (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", B_transpose_A_transpose)

transpose_property_holds = np.array_equal(AB_transpose, B_transpose_A_transpose)
print("Does (AB)^T equal B^T * A^T?", transpose_property_holds)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Does (AB)^T equal B^T * A^T? True


In [20]:
#Task2
import numpy as np

# Defining matrices A and B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("The solution for [x, y, z] is:\n", X)

The solution for [x, y, z] is:
 [[ 2.]
 [ 1.]
 [-2.]]
